name: "综合 Bug 反馈"
description: "遇见了看起来不对劲的地方"
labels: [· Bug,新反馈]
body:
  - type: markdown
    attributes:
      value: |
        感谢您的贡献！
        请仔细填写以下内容，方便我们快速排查问题
  - type: checkboxes
    id: "yml-1"
    attributes:
      label: "检查项"
      description: "请逐个检查下列项目，并勾选确认。"
      options:
      - label: "我已在 [Issues 页面](https://github.com/Yuns-Lab/YunSchedule/issues) 中搜索，确认了这一 Bug 未被提交过。"
        required: true
  - type: textarea
    id: "yml-2"
    attributes:
      label: 描述
      description: "详细描述该 Bug 的具体表现。"
    validations:
      required: true
  - type: textarea
    id: "yml-3"
    attributes:
      label: 重现步骤（如果有）
      description: "详细描述要怎么操作才能再次触发这个 Bug。"
      value: |
        1、点击xxxx
        2、往下滚，然后点击xxxx
  - type: textarea
    id: "yml-4"
    attributes:
      label: 截图（必须） / 日志（如有）
      placeholder: "先点击这个文本框，然后直接黏贴或拖动文件上传"
    validations:
      required: true
  - type: checkboxes
    id: "yml-5"
    attributes:
      label: "意向调查"
      description: "如果您愿意贡献代码来修复此 Bug，请勾选下方内容"
      options:
      - label: "我愿意为此反馈做出贡献"